spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment_service
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath*:db.changelog/changelog-master.yml
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment_service
    user: postgres
    password: postgres
app:
  jobs:
    payment-look-up-job:
      enabled: ${PAYMENT_LOOK_UP_JOB_ENABLED:false}
      cron: ${PAYMENT_LOOK_UP_JOB_CRON:0 0/5 * * * *}