spring:
  application:
    name: payment-service
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/payment_service
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath*:db.changelog/changelog-master.yml
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/payment_service
    user: postgres
    password: postgres